#### Import relevant libraries

In [ ]:
import numpy as np
import pandas as pd

#### Load data into dataframe

In [ ]:
covid_data = pd.read_csv("covid-data.csv")
#

#### Inspect the dataframe

In [ ]:
covid_data.head(5)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,24/02/2020,5,5,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,25/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,26/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,27/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,28/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [ ]:
covid_data = covid_data[['iso_code','continent','location','date','total_cases','new_cases']]

In [ ]:
covid_data.head(5)

  iso_code continent     location        date  total_cases  new_cases
0      AFG      Asia  Afghanistan  24/02/2020            5          5
1      AFG      Asia  Afghanistan  25/02/2020            5          0
2      AFG      Asia  Afghanistan  26/02/2020            5          0
3      AFG      Asia  Afghanistan  27/02/2020            5          0
4      AFG      Asia  Afghanistan  28/02/2020            5          0

In [ ]:
covid_data.dtypes

iso_code       object
continent      object
location       object
date           object
total_cases     int64
new_cases       int64
dtype: object

In [ ]:
covid_data.shape

(5818, 6)

#### Analyse the mean of the new_cases column using the mean method in numpy

In [ ]:
data_mean = np.mean(covid_data["new_cases"])
data_mean

np.float64(8814.365761430045)

#### Analyse the mean of the new_cases column using the mean method in pandas

In [ ]:
data_mean = covid_data["new_cases"].mean()
data_mean

np.float64(8814.365761430045)

Check the median of the new_cases column using the median method in numpy

In [ ]:
data_median = np.median(covid_data["new_cases"])
data_median

np.float64(261.0)

Check the median of the new_cases column using the median method in pandas

In [ ]:
data_median = covid_data["new_cases"].median()
data_median

261.0

Identify the mode of the new_cases column using the mode method

In [ ]:
from scipy import stats

In [ ]:
data_mode = covid_data["new_cases"].mode()
data_mode

0    0
Name: new_cases, dtype: int64

Identify the mode of the continent column using the mode method

In [ ]:
data_mode = covid_data["continent"].mode()
data_mode

0    Europe
Name: continent, dtype: object

Check the variance of the new_cases column using the var method in numpy

In [ ]:
data_variance = np.var(covid_data["new_cases"])
data_variance

451321915.92810047

Check the variance of the new_cases column using the var method in pandas

In [ ]:
covid_data["new_cases"].var()

451399502.6422019

Identify the standard deviation of a dataset using the std method in numpy

In [ ]:
data_sd = np.std(covid_data["new_cases"])
data_sd

21244.33844411495

Identify the standard deviation of a dataset using the std method in pandas

In [ ]:
covid_data["new_cases"].std()

21246.16442189512

Generate the range of a dataset using numpy

In [ ]:
data_max = np.max(covid_data["new_cases"])
data_min = np.min(covid_data["new_cases"])

In [ ]:
print(data_max,data_min)

287149 0

In [ ]:
data_range = data_max - data_min
data_range

287149

Generate the range of a dataset using pandas

In [ ]:
data_max = covid_data["new_cases"].max()
data_min = covid_data["new_cases"].min()

In [ ]:
data_range = data_max - data_min
data_range

287149

Identify the percentile of a dataset using numpy

In [ ]:
data_percentile = np.percentile(covid_data["new_cases"],60)
data_percentile

np.float64(591.3999999999996)

Check the quartile of a dataset using numpy

In [ ]:
data_quartile = np.quantile(covid_data["new_cases"],0.75)
data_quartile

np.float64(3666.0)

Analyse the interquartile range (IQR) of a dataset using the stats library

In [ ]:
data_IQR = stats.iqr(covid_data["new_cases"], interpolation = 'midpoint')
data_IQR

np.float64(3641.0)

In [ ]:
data_IQR = stats.iqr(covid_data["new_cases"])
data_IQR

np.float64(3642.0)